# Python w Analizie Danych
# Lab05 - Sprawozdanie

Autor: Piotr Przymus 127902

### Zadanie 1
Wczytałem dane `data_fill.json`. Sprawdziłem podstawowe informacje o danych i wyświetliłem liczbę braków danych w każdej kolumnie.

In [72]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

df = pd.read_json('data_fill.json')
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          105038 non-null  str
 3   ScheduledDay    110527 non-null  str
 4   AppointmentDay  110527 non-null  str
 5   Age             101634 non-null  float64
 6   Neighbourhood   105082 non-null  str
 7   Scholarship     101694 non-null  float64
 8   Hipertension    101740 non-null  float64
 9   Diabetes        101548 non-null  float64
 10  Alcoholism      101880 non-null  float64
 11  Handcap         101663 non-null  float64
 12  SMS_received    101895 non-null  float64
 13  No-show         110527 non-null  str
dtypes: float64(8), int64(1), str(5)
memory usage: 11.8 MB

PatientId            0
AppointmentID        0
Gender            5489
ScheduledDay         0
AppointmentDay       0
Age               8893
Neighbourhood     5445
Scholarship       8833
Hipertension      8787
Diabetes          8979
Alcoholism        8647
Handcap           8864
SMS_received      8632
No-show              0
dtype: int64

### Zadanie 2
Stworzyłem kopię danych z zadania 1. Usunąłem wszystkie wiersze, które mają braki w kolumnach `Age`, `Gender`, `Diabetes`.

In [73]:
df_2 = df.copy()
print(df_2.shape)
df_2 = df_2.dropna(subset=['Age', 'Gender', 'Diabetes'])
df_2.shape

(110527, 14)

(88689, 14)

Używając funkcji `shape()` zauważyłem, że zmniejszyła się ilość wierszy, ale ilość kolumn pozostała taka sama.

### Zadanie 3
Stworzyłem kopię danych z zadania 1.

a) Wypełniłem braki w kolumnie Age medianą.

b) Wypełniłem braki w kolumnie Scholarship wartością 0.

c) Wypełniłem braki w kolumnie Handcap metodą „forward fill”.

d) Wypełniłem braki w AppointmentDay i ScheduledDay metodą „most frequent”.

e) Wyświetliłem DataFrame po imputacji.

In [74]:
# a)
df_3 = df.copy()
df_3['Age'] = df_3['Age'].fillna(df_3['Age'].median())

In [75]:
# b)
df_3['Scholarship'] = df_3['Scholarship'].fillna(0)

In [76]:
# c)
df_3["Handcap"] = df_3["Handcap"].ffill()

In [77]:
# d)
df_3['AppointmentDay'] = df_3['AppointmentDay'].fillna(df_3['AppointmentDay'].mode()[0])
df_3['ScheduledDay'] = df_3['ScheduledDay'].fillna(df_3['ScheduledDay'].mode()[0])

In [78]:
# e)
df_3

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62.0,JARDIM DA PENHA,0.0,1.0,0.0,0.0,0.0,0.0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56.0,JARDIM DA PENHA,0.0,0.0,0.0,NaN,0.0,0.0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62.0,MATA DA PRAIA,0.0,NaN,0.0,0.0,0.0,0.0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8.0,PONTAL DE CAMBURI,0.0,0.0,0.0,0.0,0.0,0.0,No
4,8.841186e+12,5642494,NaN,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56.0,JARDIM DA PENHA,0.0,1.0,NaN,0.0,0.0,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56.0,MARIA ORTIZ,0.0,0.0,NaN,0.0,0.0,1.0,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51.0,MARIA ORTIZ,0.0,0.0,0.0,0.0,0.0,1.0,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21.0,MARIA ORTIZ,0.0,0.0,0.0,0.0,0.0,1.0,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38.0,MARIA ORTIZ,0.0,0.0,0.0,0.0,0.0,1.0,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54.0,MARIA ORTIZ,0.0,0.0,0.0,0.0,0.0,1.0,No

In [79]:
df_3.info()
df_3.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          105038 non-null  str
 3   ScheduledDay    110527 non-null  str
 4   AppointmentDay  110527 non-null  str
 5   Age             110527 non-null  float64
 6   Neighbourhood   105082 non-null  str
 7   Scholarship     110527 non-null  float64
 8   Hipertension    101740 non-null  float64
 9   Diabetes        101548 non-null  float64
 10  Alcoholism      101880 non-null  float64
 11  Handcap         110527 non-null  float64
 12  SMS_received    101895 non-null  float64
 13  No-show         110527 non-null  str
dtypes: float64(8), int64(1), str(5)
memory usage: 11.8 MB

PatientId            0
AppointmentID        0
Gender            5489
ScheduledDay         0
AppointmentDay       0
Age                  0
Neighbourhood     5445
Scholarship          0
Hipertension      8787
Diabetes          8979
Alcoholism        8647
Handcap              0
SMS_received      8632
No-show              0
dtype: int64

Porównując z informacjami wyświetlonymi w zadaniu 1 możemy zauważyć, że po zastosowaniu imputacji wyeliminowano braki danych w kolumnach w których dokonywaliśmy zmian (Age, Scholarship, Handcap, ScheduledDay, AppointmentDay).

### Zadanie 4
Usunąłem kolumny nienumeryczne, których nie da się zakodować. Dla kolumny `Gender` zmieniłem wartość `M` na 0 i `F` na 1.

In [80]:
df_3['Gender'] = df_3['Gender'].map({'M': 0, 'F': 1})
df_3 = df_3.select_dtypes(include=["number"])
df_3.head()

,PatientId,AppointmentID,Gender,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
0,2.987250e+13,5642903,1.0,62.0,0.0,1.0,0.0,0.0,0.0,0.0
1,5.589978e+14,5642503,0.0,56.0,0.0,0.0,0.0,NaN,0.0,0.0
2,4.262962e+12,5642549,1.0,62.0,0.0,NaN,0.0,0.0,0.0,0.0
3,8.679512e+11,5642828,1.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8.841186e+12,5642494,NaN,56.0,0.0,1.0,NaN,0.0,0.0,0.0

(Działałem na df_3, stąd np. braki w kolumnie `Gender`)

### Zadanie 5
Wczytałem kopię danych z pliku `data_fill.json`. Przygotowałem dane podobnie jak w poprzednich zadaniach (usunąłem wiersze z brakami danych w kolumnach `Age`, `Gender`, `Diabetes`. Zamieniłem wartości w kolumnie `Gender`. Wykorzystując bibliotekę `scikit-learn` zastosowałem wielokrotną imputację do wypełnienia brakujących danych numerycznych. Potem porównałem DataFramy z wypełnionymi danymi (`df_3` z `df_5_imputed`).

In [ ]:
df_5 = pd.read_json('data_fill.json')
df_5.dropna(inplace=True, subset=['Age', 'Gender', 'Diabetes'])
df_5['Gender'] = df_5['Gender'].map({'M': 0, 'F': 1})
df_5 = df_5.select_dtypes(include=["number"])

imputer = IterativeImputer(random_state=42, max_iter=10)
df_5_imputed = imputer.fit_transform(df_5)
df_5_imputed = pd.DataFrame(df_5_imputed, columns=df_5.columns)
df_5_imputed

In [ ]:
df_3

,PatientId,AppointmentID,Gender,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
0,2.987250e+13,5642903,1.0,62.0,0.0,1.0,0.0,0.0,0.0,0.0
1,5.589978e+14,5642503,0.0,56.0,0.0,0.0,0.0,NaN,0.0,0.0
2,4.262962e+12,5642549,1.0,62.0,0.0,NaN,0.0,0.0,0.0,0.0
3,8.679512e+11,5642828,1.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8.841186e+12,5642494,NaN,56.0,0.0,1.0,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,1.0,56.0,0.0,0.0,NaN,0.0,0.0,1.0
110523,3.596266e+12,5650093,1.0,51.0,0.0,0.0,0.0,0.0,0.0,1.0
110524,1.557663e+13,5630692,1.0,21.0,0.0,0.0,0.0,0.0,0.0,1.0
110525,9.213493e+13,5630323,1.0,38.0,0.0,0.0,0.0,0.0,0.0,1.0
110526,3.775115e+14,5629448,1.0,54.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
print(df_3.shape)
print(df_5_imputed.shape)

(110527, 10)
(88689, 10)

W df_5_imputed jest mniej rekordów niż w df_3 z powodu usunięcia wierszy z brakami danych w kolumnach `Age`, `Gender`, `Diabetes` przed użyciem Imputera. W df_3 te wiersze nadal są obecne, ale mają braki danych.

In [ ]:
print("----- Różnice w Scholarship -----")
print(df_3['Scholarship'].nunique())
print(df_5_imputed['Scholarship'].nunique())
print("----- Różnice w Hipertension -----")
print(df_3['Hipertension'].nunique())
print(df_5_imputed['Hipertension'].nunique())
print("----- Różnice w Alcoholism -----")
print(df_3['Alcoholism'].nunique())
print(df_5_imputed['Alcoholism'].nunique())
print("----- Różnice w Handcap -----")
print(df_3['Handcap'].nunique())
print(df_5_imputed['Handcap'].nunique())
print("----- Różnice w SMS_received -----")
print(df_3['SMS_received'].nunique())
print(df_5_imputed['SMS_received'].nunique())

----- Różnice w Scholarship -----
2
7121
----- Różnice w Hipertension -----
2
7000
----- Różnice w Alcoholism -----
2
6935
----- Różnice w Handcap -----
5
7162
----- Różnice w SMS_received -----
2
6914

Podliczyłem liczbę unikalnych wartości w kolumnach `Scholarship`, `Hipertension`, `Alcoholism`, `Handcap` oraz `SMS_received` i zauważyłem, że IterativeImputer wypełnił braki wyliczonymi pośrednimi wartościami. W df_3 te kolumny mają braki danych, ale w df_5_imputed są wypełnione wartościami, które niekoniecznie odpowiadają oryginalnym kategoriom binarnym (poza kolumną `Handcap` która ma 5 unikalnych wartości). IterativeImputer traktuje te kolumny jako numeryczne a tym samym zmienne ciągłe i powoduje utratę logicznej interpretacji wartości w tych kolumnach.

W przypadku takich kolumn lepszym rozwiązaniem byłoby zastosowanie innej metody imputacji, np. zastosowanie modelu klasyfikacyjnego do przewidywania brakujących wartości na podstawie innych cech, oczywiście jest to już bardziej zaawansowane podejście.