# Język Python w Analizie Danych
#

### Zadanie 1
Wczytałem dane `data_fill.json`. Sprawdziłem podstawowe informacje o danych i wyświetliłem liczbę braków danych w każdej kolumnie.

In [128]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

df = pd.read_json('data_fill.json')
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          105038 non-null  str
 3   ScheduledDay    110527 non-null  str
 4   AppointmentDay  110527 non-null  str
 5   Age             101634 non-null  float64
 6   Neighbourhood   105082 non-null  str
 7   Scholarship     101694 non-null  float64
 8   Hipertension    101740 non-null  float64
 9   Diabetes        101548 non-null  float64
 10  Alcoholism      101880 non-null  float64
 11  Handcap         101663 non-null  float64
 12  SMS_received    101895 non-null  float64
 13  No-show         110527 non-null  str
dtypes: float64(8), int64(1), str(5)
memory usage: 11.8 MB

PatientId            0
AppointmentID        0
Gender            5489
ScheduledDay         0
AppointmentDay       0
Age               8893
Neighbourhood     5445
Scholarship       8833
Hipertension      8787
Diabetes          8979
Alcoholism        8647
Handcap           8864
SMS_received      8632
No-show              0
dtype: int64

### Zadanie 2
Stworzyłem kopię danych z zadania 1. Usunąłem wszystkie wiersze, które mają braki w kolumnach `Age`, `Gender`, `Diabetes`. Używając funkcji `shape()` zauważyłem, że zmniejszyła się ilość wierszy, ale ilość kolumn pozostała taka sama.

In [129]:
df_2 = df.copy()
print(df_2.shape)
df_2 = df_2.dropna(subset=['Age', 'Gender', 'Diabetes'])
df_2.shape

(110527, 14)

(88689, 14)

### Zadanie 3
Stworzyłem kopię danych z zadania 1.

a) Wypełniłem braki w kolumnie Age medianą.

b) Wypełniłem braki w kolumnie Scholarship wartością 0.

c) Wypełniłem braki w kolumnie Handcap metodą „forward fill”.

d) Wypełniłem braki w AppointmentDay i ScheduledDay metodą „most frequent”.

e) Wyświetliłem DataFrame po imputacji.

In [130]:
# a)
df_3 = df.copy()
df_3['Age'] = df_3['Age'].fillna(df_3['Age'].median())

In [131]:
# b)
df_3['Scholarship'] = df_3['Scholarship'].fillna(0)

In [132]:
# c)
df_3["Handcap"] = df_3["Handcap"].ffill()

In [133]:
# d)
df_3['AppointmentDay'] = df_3['AppointmentDay'].ffill()
df_3['ScheduledDay'] = df_3['ScheduledDay'].ffill()

In [ ]:
# e)
df_3

,PatientId,AppointmentID,Gender,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
0,2.987250e+13,5642903,1.0,62.0,0.0,1.0,0.0,0.0,0.0,0.0
1,5.589978e+14,5642503,0.0,56.0,0.0,0.0,0.0,NaN,0.0,0.0
2,4.262962e+12,5642549,1.0,62.0,0.0,NaN,0.0,0.0,0.0,0.0
3,8.679512e+11,5642828,1.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8.841186e+12,5642494,NaN,56.0,0.0,1.0,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,1.0,56.0,0.0,0.0,NaN,0.0,0.0,1.0
110523,3.596266e+12,5650093,1.0,51.0,0.0,0.0,0.0,0.0,0.0,1.0
110524,1.557663e+13,5630692,1.0,21.0,0.0,0.0,0.0,0.0,0.0,1.0
110525,9.213493e+13,5630323,1.0,38.0,0.0,0.0,0.0,0.0,0.0,1.0
110526,3.775115e+14,5629448,1.0,54.0,0.0,0.0,0.0,0.0,0.0,1.0

In [147]:
df_3.info()
df_3.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   PatientId      110527 non-null  float64
 1   AppointmentID  110527 non-null  int64
 2   Gender         105038 non-null  float64
 3   Age            110527 non-null  float64
 4   Scholarship    110527 non-null  float64
 5   Hipertension   101740 non-null  float64
 6   Diabetes       101548 non-null  float64
 7   Alcoholism     101880 non-null  float64
 8   Handcap        110527 non-null  float64
 9   SMS_received   101895 non-null  float64
dtypes: float64(9), int64(1)
memory usage: 8.4 MB

PatientId           0
AppointmentID       0
Gender           5489
Age                 0
Scholarship         0
Hipertension     8787
Diabetes         8979
Alcoholism       8647
Handcap             0
SMS_received     8632
dtype: int64

Porównując z informacjami wyświetlonymi w zadaniu 1 możemy zauważyć, że po zastosowaniu imputacji wyeliminowano braki danych w kolumnach w których dokonywaliśmy zmian (Age, Scholarship, Handcap, ScheduledDay, AppointmentDay).

### Zadanie 4
Usunąłem kolumny nienumeryczne, których nie da się zakodować. Dla kolumny `Gender` zmieniłem wartość `M` na 0 i `F` na 1.

In [148]:
df_3['Gender'] = df_3['Gender'].map({'M': 0, 'F': 1})
df_3 = df_3.select_dtypes(include=["number"])
df_3.head()

,PatientId,AppointmentID,Gender,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
0,2.987250e+13,5642903,NaN,62.0,0.0,1.0,0.0,0.0,0.0,0.0
1,5.589978e+14,5642503,NaN,56.0,0.0,0.0,0.0,NaN,0.0,0.0
2,4.262962e+12,5642549,NaN,62.0,0.0,NaN,0.0,0.0,0.0,0.0
3,8.679512e+11,5642828,NaN,8.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8.841186e+12,5642494,NaN,56.0,0.0,1.0,NaN,0.0,0.0,0.0

(Nie było wskazane na którym dataframie działać - działałem na 3, stąd np. braki w kolumnie `Gender`)

### Zadanie 5
Wczytaj kopię danych z pliku `data_fill.json`. Przygotuj dane podobnie jak w poprzednich zadaniach (usuń dane, zamień wartości), ale nie wypełniaj danych. Wykorzystując bibliotekę `scikit-learn` zastosuj wielokrotną imputację do wypełnienia brakujących danych numerycznych. Porównaj DataFramy z wypełnionymi danymi.

In [150]:
df_5 = pd.read_json('data_fill.json')
df_5.dropna(inplace=True, subset=['Age', 'Gender', 'Diabetes'])
df_5['Gender'] = df_5['Gender'].map({'M': 0, 'F': 1})
df_5 = df_5.select_dtypes(include=["number"])

imputer = IterativeImputer(random_state=42, max_iter=10)
df_5_imputed = imputer.fit_transform(df_5)
df_5_imputed = pd.DataFrame(df_5_imputed, columns=df_5.columns)
df_5_imputed

,PatientId,AppointmentID,Gender,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
0,2.987250e+13,5642903.0,1.0,62.0,0.000000,1.000000,0.0,0.00000,0.000000,0.0
1,5.589978e+14,5642503.0,0.0,56.0,0.000000,0.000000,0.0,0.06708,0.000000,0.0
2,4.262962e+12,5642549.0,1.0,62.0,0.083493,0.334917,0.0,0.00000,0.000000,0.0
3,8.679512e+11,5642828.0,1.0,8.0,0.000000,0.000000,0.0,0.00000,0.000000,0.0
4,9.598513e+13,5626772.0,1.0,76.0,0.000000,1.000000,0.0,0.00000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...
88684,3.635534e+13,5651072.0,1.0,53.0,0.000000,0.000000,0.0,0.00000,0.000000,1.0
88685,3.596266e+12,5650093.0,1.0,51.0,0.000000,0.000000,0.0,0.00000,0.000000,1.0
88686,1.557663e+13,5630692.0,1.0,21.0,0.000000,0.000000,0.0,0.00000,0.000000,1.0
88687,9.213493e+13,5630323.0,1.0,38.0,0.000000,0.000000,0.0,0.00000,0.008702,1.0
88688,3.775115e+14,5629448.0,1.0,54.0,0.000000,0.000000,0.0,0.00000,0.000000,1.0